### ISSUE TITLE
[BUG] IF crashes on a multiple contigs file 

### ISSUE THREAD

**Issue by eloilit** [gem-pasteur/Integron_Finder#103]
**Describe the bug**
IF crashes on a multiple contigs file, using the gembase format, in the middle of the contigs being processed.

**To Reproduce**
1. integron_finder --local-max --mute --outdir ./IFResults --gembase --gembase-path ./VibrionaceaDBMarch2022_v2 --gbk ./VibrionaceaDBMarch2022_v2/Replicons/VIBR.0322.11443.fna
2. See error

I located the files to reproduce the error in /pasteur/appa/scratch/elittner/for_issue_IF_crashes 
**Expected behavior**

Normal completion

**Screenshots**

Traceback (most recent call last):
  File "/Users/eloi/Documents/Softwares/anaconda3/envs/IFv2.0.1/bin/integron_finder", line 10, in <module>
    sys.exit(main())
  File "/Users/eloi/Documents/Softwares/anaconda3/envs/IFv2.0.1/lib/python3.9/site-packages/integron_finder/scripts/finder.py", line 648, in main
    integron_res, summary = find_integron_in_one_replicon(replicon, config)
  File "/Users/eloi/Documents/Softwares/anaconda3/envs/IFv2.0.1/lib/python3.9/site-packages/integron_finder/scripts/finder.py", line 385, in find_integron_in_one_replicon
    integrons = find_integron(replicon, protein_db, integron_max, intI_file, phageI_file, config)
  File "/Users/eloi/Documents/Softwares/anaconda3/envs/IFv2.0.1/lib/python3.9/site-packages/integron_finder/integron.py", line 150, in find_integron
    attc_left = np.array([i_attc.pos_beg.values[0] for i_attc in attc_ac])
  File "/Users/eloi/Documents/Softwares/anaconda3/envs/IFv2.0.1/lib/python3.9/site-packages/integron_finder/integron.py", line 150, in <listcomp>
    attc_left = np.array([i_attc.pos_beg.values[0] for i_attc in attc_ac])
IndexError: index 0 is out of bounds for axis 0 with size 0

**Please complete the following information):**

***OS:*** 

 - [ ] Linux
 - [ ] Windows
 - [X] Mac

***Integron_Finder Version:***

integron_finder version 2.0.2
Using:
 - Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)  [Clang 13.0.1 ]
 - numpy 1.19.4
 - pandas 1.1.5
 - matplolib 3.3.3
 - biopython 1.78

 - Prodigal V2.6.3: February, 2016
 - INFERNAL 1.1.4 (Dec 2020)
 - HMMER 3.3.2 (Nov 2020); http://hmmer.org/

**Additional context**
Only one example failing over a big dataset

**Comment by eloilit** [comment]
[VibrionaceaDBMarch2022_v2.zip](https://github.com/gem-pasteur/Integron_Finder/files/9784165/VibrionaceaDBMarch2022_v2.zip)

command used: integron_finder --local-max --mute --outdir ./IFResults --gembase --gembase-path ./VibrionaceaDBMarch2022_v2 --gbk ./VibrionaceaDBMarch2022_v2/Replicons/VIBR.0322.11443.0157.fna

@jeanrjc Here are the files to reproduce the error
