### ISSUE TITLE
Runtime error on draft assemblies

### ISSUE THREAD

**Issue by lowandrew** [gem-pasteur/Integron_Finder#58]
## Version of Integron_Finder:
```
integron_finder version 2.0rc5
Using:    
 - Python 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 18:15:35)  [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
 - numpy 1.15.4
 - pandas 0.23.4
 - matplolib 3.0.2
 - biopython 1.72

Authors:
 - Jean Cury, Bertrand Neron, Eduardo Rocha,

Citation:

 Identification and analysis of integrons and cassette arrays in bacterial genomes
 Jean Cury; Thomas Jove; Marie Touchon; Bertrand Neron; Eduardo PC Rocha
 Nucleic Acids Research 2016; doi: 10.1093/nar/gkw319
```

### OS

- [X] Linux
- [ ] Windows
- [ ] Mac

## Expected behavior

When attempting to run `integron_finder` on draft assemblies, some of my fairly small contigs (2000ish base pairs) don't have any proteins found. I'd expect that `integron_finder` would just skip over these contigs without crashing the program. 

## Actual behavior

I hit a `RuntimeError` similar to the following:
```
CRITICAL :  The protein file: '/home/lowa/test_integron/Results_Integron_Finder_2014-SEQ-0276/other_Contig_23_699.663/Contig_23_699.663.prt' is empty cannot perform hmmsearch on it.
Traceback (most recent call last):
  File "/home/lowa/miniconda3/envs/integron_finder/bin/integron_finder", line 11, in <module>
    sys.exit(main())
  File "/home/lowa/miniconda3/envs/integron_finder/lib/python3.7/site-packages/integron_finder/scripts/finder.py", line 578, in main
    integron_res, summary = find_integron_in_one_replicon(replicon, config)
  File "/home/lowa/miniconda3/envs/integron_finder/lib/python3.7/site-packages/integron_finder/scripts/finder.py", line 302, in find_integron_in_one_replicon
    find_integrase(tmp_replicon_path, replicon, prot_file, result_dir_other, config)
  File "/home/lowa/miniconda3/envs/integron_finder/lib/python3.7/site-packages/integron_finder/integrase.py", line 75, in find_integrase
    raise RuntimeError(msg)
RuntimeError: The protein file: '/home/lowa/test_integron/Results_Integron_Finder_2014-SEQ-0276/other_Contig_23_699.663/Contig_23_699.663.prt' is empty cannot perform hmmsearch on it.
```
As it is, I can get `integron_finder` to run by removing the offending contigs, but if possible I'd prefer that I don't have to pre-filter my draft assemblies.

## Steps to reproduce behavior

Run the following command on the file attached:

`integron_finder --local-max --cpu 12 --outdir test_integron 2014-SEQ-0276.fasta` 

[2014-SEQ-0276.fasta.txt](https://github.com/gem-pasteur/Integron_Finder/files/2620896/2014-SEQ-0276.fasta.txt)

## Relevant logs and/or screenshots

Log file attached.

[integron_finder.out.txt](https://github.com/gem-pasteur/Integron_Finder/files/2620907/integron_finder.out.txt)

Thanks in advance for your help!

**Comment by lowandrew** [comment]
Looks like this is just a problem with the latest release - if I go from the master branch I don't get the error.
