### ISSUE TITLE
conda install causes pandas.io.common ImportError

### ISSUE THREAD

**Issue by nebfield** [gem-pasteur/Integron_Finder#77]
Hello,

If I follow the instructions to install `integron_finder` with conda:

```
conda install -c defaults -c conda-forge -c bioconda integron_finder
```

And run `integron_finder -h` to test the install, I get the following ImportError:

```
Traceback (most recent call last):
  File "/home/ben/.conda/envs/integronfinder/bin/integron_finder", line 7, in <module>
    from integron_finder.scripts.finder import main
  File "/home/ben/.conda/envs/integronfinder/lib/python3.8/site-packages/integron_finder/scripts/finder.py", line 52, in <module>
    from integron_finder import results
  File "/home/ben/.conda/envs/integronfinder/lib/python3.8/site-packages/integron_finder/results.py", line 29, in <module>
    from pandas.io.common import EmptyDataError
ImportError: cannot import name 'EmptyDataError' from 'pandas.io.common' (/home/ben/.conda/envs/integronfinder/lib/python3.8/site-
packages/pandas/io/common.py)
```

Manually downgrading pandas fixes the error :tada:

```
conda install pandas=0.25.3
...
integron_finder -V
integron_finder version 2.0rc6
Using:
 - Python 3.8.5 | packaged by conda-forge | (default, Jul 31 2020, 02:39:48)  [GCC 7.5.0]
 - numpy 1.19.1
 - pandas 0.25.3
 - matplolib 3.3.1
 - biopython 1.77

Authors:
 - Jean Cury, Bertrand Neron, Eduardo Rocha,

Citation:

 Identification and analysis of integrons and cassette arrays in bacterial genomes
 Jean Cury; Thomas Jove; Marie Touchon; Bertrand Neron; Eduardo PC Rocha
 Nucleic Acids Research 2016; doi: 10.1093/nar/gkw319
``` 

Cheers,
Ben

**Comment by nebfield** [comment]
Also, if you get an error about:

```
AttributeError: module 'Bio.Seq' has no attribute 'IUPAC'
```

Then: 

```
conda install biopython==1.72
```

will fix the issue :smile:

**Comment by jeanrjc** [comment]
Yes, see issue #78 for clean solution of the same problem.
