### ISSUE TITLE
error on calling --gembases option

### ISSUE THREAD

**Issue by cachapuz2001** [gem-pasteur/Integron_Finder#80]
## Version of Integron_Finder:

integron_finder version 2.0rc6

### OS

- [ ] Linux
- [ ] Windows
- [X ] Mac

## Expected behavior

Should work search for .lst file in /Users/erocha/Genomes/Genomes/LSTINF/

## Actual behavior

Searches for .lst file in /Users/erocha/Genomes/Genomes/LSTINFO/ which does not exist. (it's just an issue of an extra "O")

## Steps to reproduce behavior

I think the problem in Integron_Finder/integron_finder/prot_db.py (line 186)
        lst_dir_path = os.path.join(gembase_path, 'LSTINFO’)
Which should be:
        lst_dir_path = os.path.join(gembase_path, 'LSTINF’)

## Relevant logs and/or screenshots

(Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's very hard to read otherwise.)

INFO     :  ############ Processing replicon ESCO001.D.00001.C001 (1/1) ############

Traceback (most recent call last):
  File "/Users/erocha/opt/miniconda3/envs/IFv2/bin/integron_finder", line 10, in <module>
    sys.exit(main())
  File "/Users/erocha/opt/miniconda3/envs/IFv2/lib/python3.6/site-packages/integron_finder/scripts/finder.py", line 595, in main
    integron_res, summary = find_integron_in_one_replicon(replicon, config)
  File "/Users/erocha/opt/miniconda3/envs/IFv2/lib/python3.6/site-packages/integron_finder/scripts/finder.py", line 294, in find_integron_in_one_replicon
    protein_db = GembaseDB(replicon, config)
  File "/Users/erocha/opt/miniconda3/envs/IFv2/lib/python3.6/site-packages/integron_finder/prot_db.py", line 134, in __init__
    self._info = self._parse_lst()
  File "/Users/erocha/opt/miniconda3/envs/IFv2/lib/python3.6/site-packages/integron_finder/prot_db.py", line 248, in _parse_lst
    gembase_type = self.gembase_sniffer(lst_path)
  File "/Users/erocha/opt/miniconda3/envs/IFv2/lib/python3.6/site-packages/integron_finder/prot_db.py", line 173, in gembase_sniffer
    with open(lst_path) as lst_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/erocha/Genomes/Genomes/LSTINFO/ESCO001.D.00001.C001.lst'

**Comment by bneron** [comment]
fixed and merge in dev branch
