### ISSUE TITLE
some major and common problems 

### ISSUE THREAD

**Issue by hongyuan-zheng** [gem-pasteur/Integron_Finder#81]
## Version of Integron_Finder:

Linux

## Expected behavior

verify integrons in some strains which have been assembled to contigs

## Actual behavior

integron_finder --local-max --func-annot --cpu 5 --gbk mysequence.fa

## Relevant logs and/or screenshots

**1. if the parameter --gbk was added ,the error below often occured:**
Traceback (most recent call last):
  File "/User/zhenghy/software/conda/miniconda/envs/IFv2/bin/integron_finder", line 10, in <module>
    sys.exit(main())
  File "/User/zhenghy/software/conda/miniconda/envs/IFv2/lib/python3.6/site-packages/integron_finder/scripts/finder.py", line 595, in main
    integron_res, summary = find_integron_in_one_replicon(replicon, config)
  File "/User/zhenghy/software/conda/miniconda/envs/IFv2/lib/python3.6/site-packages/integron_finder/scripts/finder.py", line 392, in find_integron_in_one_replicon
    add_feature(replicon, integrons_report, protein_db, config.distance_threshold)
  File "/User/zhenghy/software/conda/miniconda/envs/IFv2/lib/python3.6/site-packages/integron_finder/annotation.py", line 183, in add_feature
    f1 = SeqFeature.FeatureLocation(start_integron_1 - 1, end_integron_1)
  File "/User/zhenghy/software/conda/miniconda/envs/IFv2/lib/python3.6/site-packages/Bio/SeqFeature.py", line 750, in __init__
    self.start))
**ValueError: End location (1532003) must be greater than or equal to start location (1900396)** 
I did nothing except inputted the multi-fasta file as the input file.

**2. if the input file was a multi-fasta ,the error below often occured:**
Traceback (most recent call last):
  File "/User/zhenghy/software/conda/miniconda/envs/IFv2/bin/integron_finder", line 10, in <module>
    sys.exit(main())
  File "/User/zhenghy/software/conda/miniconda/envs/IFv2/lib/python3.6/site-packages/integron_finder/scripts/finder.py", line 595, in main
    integron_res, summary = find_integron_in_one_replicon(replicon, config)
  File "/User/zhenghy/software/conda/miniconda/envs/IFv2/lib/python3.6/site-packages/integron_finder/scripts/finder.py", line 332, in find_integron_in_one_replicon
    evalue_attc=config.evalue_attc)
  File "/User/zhenghy/software/conda/miniconda/envs/IFv2/lib/python3.6/site-packages/integron_finder/attc.py", line 213, in find_attc_max
    **go_left = (full_element[full_element.type_elt == "attC"].pos_beg.values[0] - df_max.pos_end.values[0]**
**IndexError: index 0 is out of bounds for axis 0 with size 0**
also, I did nothing except inputted the multi-fasta file as the input file.

**3. what dose the third column "element" mean in the output file "mysequence.integrons" ??**
**4. whould you please output a file of the fasta sequence of the verified integrons ??**

**Comment by jeanrjc** [comment]
Hello,
Sorry I did not see your issue when you posted it. 

1. If you could share the sequence causing the issue, it will be easier for us to debug.
2. See error #73 and see whether it solve your issue. 
3. elements are the identifiers of different type of elements (in column type_elt), such as attC/I sites, promoters, or proteins.  
4. IntegronFinder does not output fasta files, but gbk files (which should work normally). You can easily reconstruct fasta file from your input sequence and the table of positions. Feel free to propose a merge request to add this feature. 

Best

**Comment by jeanrjc** [comment]
Without more details, I'm closing this issue. Feel free to add the details, and I'll reopen it.
