### ISSUE TITLE
ValueError: attempt to get argmin of an empty sequence

### ISSUE THREAD

**Issue by danyu-uofa** [gem-pasteur/Integron_Finder#92]
## Version of Integron_Finder:

integron_finder version 2.0rc9
Using:    
 - Python 3.9.5 (default, May 11 2021, 08:20:37)  [GCC 10.3.0]
 - numpy 1.19.5
 - pandas 1.1.5
 - matplolib 3.3.4
 - biopython 1.79

### OS

- [X] Linux
- [ ] Windows
- [ ] Mac

## Expected behavior

I am running integron_finder on a set of _E. coli_ genomes using the ```--local-max``` and ```--func-annot``` options and it works fine for most of them. 

## Actual behavior

During the integron search for select strains, however, the program will be able to search some replicons for integrons but will fail and exit early, returning (also see screenshot below):

```
Traceback (most recent call last):
  File "/usr/local/bin/integron_finder", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/integron_finder/scripts/finder.py", line 607, in main
    integron_res, summary = find_integron_in_one_replicon(replicon, config)
  File "/usr/local/lib/python3.9/dist-packages/integron_finder/scripts/finder.py", line 324, in find_integron_in_one_replicon
    integrons = find_integron(replicon, protein_db, attC_default_file, intI_file, phageI_file, config)
  File "/usr/local/lib/python3.9/dist-packages/integron_finder/integron.py", line 80, in find_integron
    phageI = read_hmm(replicon.id, prot_db, phageI_file, cfg)
  File "/usr/local/lib/python3.9/dist-packages/integron_finder/hmm.py", line 150, in read_hmm
    best_evalue = np.argmin(evalue_tmp)
  File "<__array_function__ internals>", line 5, in argmin
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 1269, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 55, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 44, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
```

## Steps to reproduce behavior

I downloaded the genome sequence of _E. coli_ strain M505 from NCBI via the following accession number: GCF_013374235.2

I then ran integron finder with the ```--local-max``` and ```--func-annot``` options.

## Relevant logs and/or screenshots

![Screen Shot 2021-08-09 at 9 13 53 PM](https://user-images.githubusercontent.com/71295660/128803356-f686828d-b5b4-495c-bd4b-cf1b19110ac1.png)

Apologies if this isn't clear enough, I am relatively new to bioinformatics and wanted to try out integron_finder.

**Comment by bneron** [comment]
I fixed the problem, and push it on *dev* branch.
I will soon create a new release with this fix.
But meanwhile if you want to try it, you can install integron_finder directly from the repository.

to do that in a virtuallenv follow the procedure below

```
python3 -m venv if_venv
cd if_venv
source bin/activate
python -m pip install git+https://github.com/gem-pasteur/Integron_Finder.git@2c9ac8353388e2c6cca8bf56e5656026fd21696b
```
thank's to report us this problem,

**Comment by bneron** [comment]
I fixed the problem, and push it on *dev* branch.
I will soon create a new release with this fix.
But meanwhile if you want to try it, you can install integron_finder directly from the repository.

to do that in a virtuallenv follow the procedure below

```
python3 -m venv if_venv
cd if_venv
source bin/activate
python -m pip install git+https://github.com/gem-pasteur/Integron_Finder.git@2c9ac8353388e2c6cca8bf56e5656026fd21696b
```
thank's to report us this problem,

**Comment by danyu-uofa** [comment]
Thank you!

**Comment by susheelbhanu** [comment]
Hi I'm running into the same issue with the latest version from conda:
```bash
Traceback (most recent call last):
  File "/hdd0/susbus/tools/conda_env/3cd81d02c5745c3080088a3e91542550_/bin/integron_finder", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/hdd0/susbus/tools/conda_env/3cd81d02c5745c3080088a3e91542550_/lib/python3.12/site-packages/integron_finder/scripts/finder.py", line 651, in main
    integron_res, summary = find_integron_in_one_replicon(replicon, config)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hdd0/susbus/tools/conda_env/3cd81d02c5745c3080088a3e91542550_/lib/python3.12/site-packages/integron_finder/scripts/finder.py", line 357, in find_integron_in_one_replicon
    integrons = find_integron(replicon, protein_db, intI_file, phageI_file, config, attc_file=attC_default_file)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hdd0/susbus/tools/conda_env/3cd81d02c5745c3080088a3e91542550_/lib/python3.12/site-packages/integron_finder/integron.py", line 187, in find_integron
    side = np.argmin(distances)
           ^^^^^^^^^^^^^^^^^^^^
  File "/hdd0/susbus/tools/conda_env/3cd81d02c5745c3080088a3e91542550_/lib/python3.12/site-packages/numpy/core/fromnumeric.py", line 1325, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hdd0/susbus/tools/conda_env/3cd81d02c5745c3080088a3e91542550_/lib/python3.12/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
ValueError: attempt to get argmin of an empty sequence
```

**Comment by mberacochea** [comment]
Hi,

We bumped into this problem,
```bash
10884_5kb_contigs/tmp_contig_2536 : [Errno 39] Directory not empty: '/xxxxx/nextflow-workdir/ERP148499/map_v6/c495b6b7-dc61-49c8-9ec9-60c35a091ef3/de/1d18abe73029534128323601afbffd/Results_Integron_Finder_ERZ19210884_5kb_contigs/tmp_contig_2536''ESC[0m
ESC[32mINFO     : ESC[0m ############ Processing replicon contig_2537 (2537/10395) ############
ESC[0m
ESC[32mINFO     : ESC[0m Starting Default search ... :ESC[0m
ESC[32mINFO     : ESC[0m Default search done... : ESC[0m
Traceback (most recent call last):
  File "/usr/local/bin/integron_finder", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/local/lib/python3.13/site-packages/integron_finder/scripts/finder.py", line 653, in main
    integron_res, summary = find_integron_in_one_replicon(replicon, config)
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/integron_finder/scripts/finder.py", line 358, in find_integron_in_one_replicon
    integrons = find_integron(replicon, protein_db, intI_file, phageI_file, config, attc_file=attC_default_file)
  File "/usr/local/lib/python3.13/site-packages/integron_finder/integron.py", line 191, in find_integron
    side = np.argmin(distances)
  File "/usr/local/lib/python3.13/site-packages/numpy/_core/fromnumeric.py", line 1440, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
  File "/usr/local/lib/python3.13/site-packages/numpy/_core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
```
