### ISSUE TITLE
Issue with colorlog logging

### ISSUE THREAD

**Issue by alexweisberg** [gem-pasteur/Integron_Finder#93]
## Version of Integron_Finder:

integron_finder version 2-2021-09-27
Using:
 - Python 3.7.2 (default, Feb  9 2019, 23:04:15)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
 - numpy 1.20.2
 - pandas 1.1.3
 - matplolib 3.0.3
 - biopython 1.76

Authors:
 - Jean Cury, Bertrand Neron, Eduardo Rocha,

Citation:

 Identification and analysis of integrons and cassette arrays in bacterial genomes
 Jean Cury; Thomas Jove; Marie Touchon; Bertrand Neron; Eduardo PC Rocha
 Nucleic Acids Research 2016; doi: 10.1093/nar/gkw319

### OS

- [X] Linux
- [ ] Windows
- [ ] Mac

## Expected behavior

Running of integron_finder

## Actual behavior

Running integron_finder with python3 after installing with pip from github gives the following error:

```
python3 /myhomefolder/.local/bin/integron_finder -v genome.fa
Traceback (most recent call last):
  File "/myhomefolder/.local/bin/integron_finder", line 8, in <module>
    sys.exit(main())
  File "/myhomefolder/.local/lib/python3.7/site-packages/integron_finder/scripts/finder.py", line 521, in main
    out=not config.mute)
  File "/myhomefolder/.local/lib/python3.7/site-packages/integron_finder/__init__.py", line 78, in init_logger
    logging = colorlog.logging.logging
AttributeError: module 'colorlog' has no attribute 'logging'
```
The colorlog module appears to be up to date (version 6.4.1). Thank you!

**Comment by alexweisberg** [comment]
It turns out this issue is due to changes in a recent version of colorlog. Colorlog version [6.4.1](https://github.com/borntyping/python-colorlog/releases/tag/v6.4.1) has renamed the colorlog.logging function to colorlog.wrappers. Installing an earlier version of colorlog doesn't have this issue.
